# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Run linter (ruff)
        run: uv run ruff thepackage

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: python -m pip install uv

      - name: Setup venv
        run: uv venv --python 3.14

      - name: Install dependencies
        run: uv pip install . --group lint

      - name: Lint with flake8
        run: uv run flake8

  batch_test:
    name: Batch Test
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: python -m pip install uv

      - name: Setup venv
        run: uv venv --python ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv pip install . --group test

      - name: Test with pytest
        run: uv run python -m pytest --rootdir=${{ github.workspace }} tes

  version:
    name: Semantic Version
    needs: batch_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Calculate Version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v2
        with:
          initial_version: 0.1.0

      - name: Echo Version
        run: 'echo "Calculated version: ${{ steps.calculate-version.outputs.version-string }}"'
