# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint_source:
    name: Lint Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run linter (ruff)
        run: uv run ruff check

  lint_commit:
    name: Lint Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commitlint
        uses: opensource-nepal/commitlint@v1

  batch_test:
    name: Batch Test
    needs: [lint_source, lint_commit]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.14"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Setup venv
        run: uv venv --python ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv pip install . --group test

      - name: Test with pytest
        run: uv run python -m pytest --rootdir=${{ github.workspace }} test

  version:
    name: Semantic Version
    needs: lint_commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Calculate Version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v2
        with:
          initial_version: 0.1.0

      - name: Echo Version
        run: 'echo "Calculated version: ${{ steps.calculate-version.outputs.version-string }}"'

      - name: Update Version File
        run: echo "version=${{ steps.calculate-version.outputs.version-string }}" > envpy/_version.py

  build:
    name: Build Package
    needs: [batch_test, version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Setup venv
        run: uv venv --python 3.14

      - name: Install dependencies
        run: uv pip install . --group lint

      - name: Build (uv)
        run: uv build

  commit_version:
    name: Commit Version FIle
    needs: [batch_test, version]
    runs-on: ubuntu-latest
    steps:
      - name: Configure user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Stage Changes
        run: git add .

      - name: Commit
        run: |
          git commit -m 'chore: update version file'

      - name: Push
        run: git push
